## Intro to numpy

In [23]:
import numpy as np
import random

In [2]:
x = [1,2,3,4,5]

In [3]:
x

[1, 2, 3, 4, 5]

In [4]:
y = np.array(x)

In [5]:
print(x[0])
print(y[0])

1
1


In [6]:
print(x[::2])
print(y[::2])

[1, 3, 5]
[1 3 5]


## Operasi Matrix

In [7]:
y + y

array([ 2,  4,  6,  8, 10])

## From tuple to numpy array

In [8]:
z = (1,2,3)
a = np.array(z)

print(z)
print(a)

(1, 2, 3)
[1 2 3]


## Slicing

In [33]:
x = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
y = np.array(x)

print(y[1][1])
print(y[1,1])

5
5


In [39]:
print(y[0:,[0,2]])
print(y[0:,1:2])

[[1 3]
 [4 6]
 [7 9]]
[[2]
 [5]
 [8]]


In [45]:
print(y[0:, :1]) # size = 3 shape=(3,1)
print('\n')
print(y[0:, :1].reshape(3,))
print('\n')
print(y[0:, 0].reshape(3,1)) # size = 3, shape=(3,)

[[1]
 [4]
 [7]]


[1 4 7]


[[1]
 [4]
 [7]]


## Dimension Check

In [10]:
y.ndim

2

In [11]:
c = [[[1,2,3], [4,5,6], [7,8,9]]]
c = np.array(c)
c.ndim

3

## Concat 2D Matrix

In [12]:
b = np.array([
    [6,7,8],
    [8,9,0]
])

In [13]:
yb = y + b

In [14]:
yb

array([[ 7,  9, 11],
       [12, 14,  6]])

## The Size of array

In [15]:
yb.size

6

## Data Type

In [16]:
yb.dtype

dtype('int32')

## Item Size (in Bytes)

In [17]:
yb.itemsize

4

## Array Shape

In [18]:
yb.shape

(2, 3)

## Array Arange

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## Array random And linspace

In [26]:
print(np.random.random(10))

[0.34057497 0.85834088 0.02407766 0.99450172 0.93517318 0.27080672
 0.96969335 0.17739784 0.31432006 0.17966698]


In [28]:
print(np.random.randint(10, size=10)) #satu dimensi 10 element

[5 8 0 5 0 2 3 2 2 0]


In [29]:
print(np.random.randint(10, size=(2,5))) #dua dimensi per dimensi lima element

[[3 0 3 4 4]
 [3 4 6 4 8]]


In [30]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [32]:
np.linspace(0, 300, 11)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.])

## Concat 2D Matrix

In [47]:
a = np.array([
    [0,-7],
    [-1,3]
])
b = np.array([
    [2,4],
    [3,8]
])

In [49]:
a+b

array([[ 2, -3],
       [ 2, 11]])

In [50]:
a-b

array([[ -2, -11],
       [ -4,  -5]])

In [52]:
a+2 #skalar

array([[ 2, -5],
       [ 1,  5]])

## Linear Algebra

## 1. Quiz
2x + y = 5

x + y = 7

berapakah x dan y?

In [59]:
a = np.array([
    [2,1],
    [1,1]
])
r = np.array([ 5, 7 ])
xy = np.linalg.solve(a,r)
print(xy)

[-2.  9.]


In [64]:
a = np.array([[3]])
r = np.array([6])
x = np.linalg.solve(a,r)
x

array([2.])

## 2. Quiz
4x + 7y = 2

3x + 2y = -5

berapakah 2x - 3y?

In [66]:
soal1 = np.array([
    [4,7],
    [3,2]
])
soal2 = np.array([
    2, -5
])

jawab = np.linalg.solve(soal1, soal2)
jawab

array([-3.,  2.])

In [69]:
x = jawab[0]
y = jawab[1]
jawaban=(2*x)-(3*y)
jawaban

-12.0

## 3. Quiz

kambing + ayam = 25

4kambing + 2ayam = 70

berapakah kambing dan ayam?

In [70]:
soal1 = np.array([
    [1,1],
    [2,4]
])
soal2 = np.array([
    25,70
])
jawaban = np.linalg.solve(soal1, soal2)
jawaban

array([15., 10.])

## 4. Quiz
Andi beli 2 buku, 1 pensil dan 1 penghapus = 4700

Budi beli 1 buku, 2 pensil dan 1 penghapus = 4300

Caca beli 3 buku, 2 pensil dan 1 penghapus = 7100

Berapakah harga 1 buku, 1 pensil dan 1 penghapus?

In [74]:
soal1 = np.array([
    [2,1,1],
    [1,2,1],
    [3,2,1]
])
soal2 = np.array([
    4700,4300,7100
])
jawaban = np.linalg.solve(soal1, soal2)
print(f'Harga 1 buku adalah {round(jawaban[0])}. Harga 1 pensil adalah {round(jawaban[1],1)}. Harga 1 penghapus adalah {round(jawaban[2],1)}')

Harga 1 buku adalah 1400.0. Harga 1 pensil adalah 1000.0. Harga 1 penghapus adalah 900.0


In [85]:
import functools
def maks_mins(a_list):
    x = np.array(a_list)
    x = np.sort(x)
    maks = x[-1]
    mins = x[0]
    sums = functools.reduce(lambda a,b: a+b, x)
    return(maks, mins, sums)

a_list=[1,3,5,6,4,2,3,5,7]
print(maks_mins(a_list))

(7, 1, 36)


In [81]:
x = np.array([1,2,3,4,5])
x = np.sort(x)
x

TypeError: sort() got an unexpected keyword argument 'reversed'